name: Deploy .NET 8 app to Azure Web App (staging)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@main

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Web App (staging)
        uses: azure/webapps-deploy@v3
        with:
          app-name: testappniedkamil777              # dokładnie jak w Azure
          slot-name: staging                         # dokładnie jak slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: ./publish